Repository katalon-studio/testops-cucumber, pull requests merged in 2021-04, with the labels that each got.

#4 [TO-1356] Create version in github using manual trigger
  .github/workflows/manual-publish.yml
Labels: Extra Small

#5 [TO-1356] Release maven in Github using manual trigger
  .github/workflows/manual-publish-release-package.yml
  .github/workflows/manual-publish.yml
  pom.xml
Labels: Medium

#6 [TO-1378] release 1.1.0
  README.md
  pom.xml
Labels: Small
